from mars_planner import mars_planner_submission
from routefinder import routefinder_submission
from antennae import antennae_submission

mars_planner_submission()
routefinder_submission()
antennae_submission()